name: build_v03

on:
  push:
    branches: [ v0.3 ]
  pull_request:
    branches: [ v0.3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies for ndncxx
      run: sudo apt-get install pkg-config libboost-all-dev libssl-dev libsqlite3-dev
    - name: prepare ndncxx
      run: |
        git clone https://github.com/named-data/ndn-cxx.git
        cd ndn-cxx
        ./waf configure
        ./waf 
        sudo ./waf install
        cd ..
    - name: configure
      run: ./waf configure --with-tests
    - name: build
      run: ./waf
    - name: install
      run: sudo ./waf install
    - name: check
      run: ./build/unit-tests
