name: build_v03

on:
  push:
    branches: [ v0.3 ]
  pull_request:
    branches: [ v0.3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./waf configure --with-tests
    - name: build
      run: ./waf
    - name: install
      run: ./waf install
    - name: check
      run: ./build/unit-tests
